### ISSUE TITLE
System.ArgumentException: The path is empty

### ISSUE THREAD

**Issue by MirisWisdom** [yumiris/YouTube.Album.Extract#1]
As reported by [Arg274 here](https://www.reddit.com/r/musichoarder/comments/q73tvv/comment/hgu0uwv/?utm_source=reddit&utm_medium=web2x&context=3):
```
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileInfo..ctor(String originalPath, String fullPath, String fileName, Boolean isNormalized)
   at System.IO.FileInfo..ctor(String fileName)
   at Gunloader.Albums.Album.Encode(Toolkit toolkit)
   at Gunloader.Program.Invoke()
   at Gunloader.Program.Main(String[] args)
```
```
chcp 65001
.\gunloader.exe --album ".\input.txt" --format raw --youtube-dl ".\YDL\yt-dlp.exe" --flac "C:\Program Files (x86)\Exact Audio Copy\Flac\flac.exe" --ffmpeg "C:\ffmpeg\bin\ffmpeg.exe" --no-prompt
pause
```

**Comment by yumiris** [comment]
Many thanks for looking into it -- I'll have a look at the chapter parsing mechanism and try to fix the issue. I'll use the video you linked to pinpoint the exact cause.

> For the first case, I'd ideally pick the video name as the album name and then proceed normally.

When using the chapters mode, the album name is already automatically set to the video name!
